[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[fmt]
sort_imports = true
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 4

[lint]
exclude_lints = [
    "mixed-case-variable",
    "screaming-snake-case-immutable",
    "mixed-case-function",
]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
morpho-vault-v2 = { version = "1.0.0", git = "https://github.com/morpho-org/vault-v2", rev = "425f6b1fb3a1d25083a9515348bd5e7bd3ab9017" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
